## -*- coding: utf-8 -*-
#"""
#/***************************************************************************
# IWD
#                                 A QGIS plugin
# This plugin detects potential illegal waste spots on a field, based on multispectral NDVI orthomosaic
# Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
#                             -------------------
#        begin                : 2025-05-12
#        copyright            : (C) 2025 by David Hovnik, OneDrone d.o.o.
#        email                : david@onedrone.si
#        git sha              : $Format:%H$
# ***************************************************************************/
#
#/***************************************************************************
# *                                                                         *
# *   This program is free software; you can redistribute it and/or modify  *
# *   it under the terms of the GNU General Public License as published by  *
# *   the Free Software Foundation; either version 2 of the License, or     *
# *   (at your option) any later version.                                   *
# *                                                                         *
# ***************************************************************************/
# This script initializes the plugin, making it known to QGIS.
#"""
#
#
## noinspection PyPep8Naming
#def classFactory(iface):  # pylint: disable=invalid-name
#    """Load IWD class from file IWD.
#
#    :param iface: A QGIS interface instance.
#    :type iface: QgsInterface
#    """
#    #
#    from .IWD import IWD
#    return IWD(iface)
#
from .IWD import IWD           # <— ime datoteke spodaj

def classFactory(iface):
    return IWD(iface)
